### ISSUE TITLE
Consider enabling https

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-vm#2]
Hi, it should be great to configure https while provisioning the box. 
To do so, the easiest solution should be to rely on the `ssl-cert` package embedded by default in Ubuntu 14.04. Then, inside provision.sh only 2 lines are required:

```
a2enmod ssl
a2ensite default-ssl.conf
```

Default prebuilt certificates are located in:
- "/etc/ssl/certs/ssl-cert-snakeoil.pem"
- "/etc/ssl/private/ssl-cert-snakeoil.key"

Finally, in the site's vhost file:

```
<VirtualHost *:443>
  ServerName juice-test.dev
  DocumentRoot /srv/www/tj-juice-test
  SSLEngine on
  SSLCertificateFile "/etc/ssl/certs/ssl-cert-snakeoil.pem"
  SSLCertificateKeyFile "/etc/ssl/private/ssl-cert-snakeoil.key"
</VirtualHost>
```

Source: http://askubuntu.com/questions/49196/how-do-i-create-a-self-signed-ssl-certificate

**Comment by ezekg** [comment]
Been wanting to do this for awhile. Wasn't aware it was this easy to set up. I'll try and get this implemented within the next week or so.

**Comment by cycomarcooo** [comment]
Realy easy, it works well on my side. I just add the apache config commands to provision.sh 
see https://github.com/cycomarcooo/theme-juice-vvv/commit/798754c9987c3e702cdea3635f49b6eb1fccfd84

**Comment by cycomarcooo** [comment]
The only remaining step is to add http support in the site.conf created by theme-juice-cli. I'm wondering if it should be a choice left to the user while creating a new site with tj create... or simply add it by default.

**Comment by ezekg** [comment]
Yep. We'd need to add it to the CLI as an option for both [Apache](https://github.com/ezekg/theme-juice-cli/blob/master/lib/theme-juice/tasks/apache.rb?ts=2) and [Nginx](https://github.com/ezekg/theme-juice-cli/blob/master/lib/theme-juice/tasks/nginx.rb?ts=2) (I believe Nginx is already set up for SSL if the VM is as well) I think having the default answer be yes during site creation would work.

**Comment by ezekg** [comment]
Do you have specific steps for adding the self-signed certs to the host's trusted keychain so I can add it to the readme once these changes are implemented?

**Comment by cycomarcooo** [comment]
Here is the official wiki page from vvv about sefl-signed cert. There are info concerning Nginx and keychain:

https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Site-specific-self-signed-SSL-certificates

**Comment by ezekg** [comment]
How did you get this to work for `https://juice-test.dev`? I've only been able to get it working for the root `https://vvv` domain. For example, appending `/etc/apache2/custom-sites/default.conf` with

``` apache
<VirtualHost *:443>
  ServerName vvv.dev
  DocumentRoot /srv/www/default
  SSLEngine on
  SSLCertificateFile "/etc/ssl/certs/ssl-cert-snakeoil.pem"
  SSLCertificateKeyFile "/etc/ssl/private/ssl-cert-snakeoil.key"
</VirtualHost>
```

does nothing. Cert for `vvv` has already been added to my Keychain. Did you do any additional steps, such as generating a cert per-domain? Trying to automate this with the CLI, so let me know. [It might be easier to use Let's Encrypt](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04), but I thought I'd touch base with you here and see how you did it.

This is the error I get from Chrome when trying to access any domain other than `https://vvv`,
![image](https://cloud.githubusercontent.com/assets/6979737/14288882/27eb8e9e-fb1e-11e5-95d1-73cd56257461.png)

It looks like the snake oil cert is only valid for `https://vvv`.

**Comment by cycomarcooo** [comment]
I think it's to much cumbersome to request Let's Encrypt certificate for each new dev project.
Of course we can generate a new self-signed certificate for each new project but you'll face a warning anyway from chrome as it self-signed.

Correct me if I'm wrong, I think we can safely use a generic certificate for all projects hosted in the same local VM.
Browsers are throwing the error you mentioned because the domain name referenced inside the certificate do not correspond to the domain which is using the certificate. That being said, that's just a warning.
To get rid of it, go to your keychain, find the certificate select "always trust". Restart Chrome and try again.

<img width="665" alt="screen shot 2016-04-05 at 19 27 23" src="https://cloud.githubusercontent.com/assets/1563647/14291984/50809f46-fb66-11e5-8009-aaa81b3aa80e.png">

Tell me if it's ok on your side.

**Comment by cycomarcooo** [comment]
With a per site self-signed cert you'll have to do the same.

**Comment by ezekg** [comment]
Yeah, I thought we could use the snake oil cert for all projects as well. I've already set the cert to always trust, but Chrome/FireFox still won't let me connect (even after restarting them). Safari doesn't give me any issues. Can you connect to `https://vvv.dev` after setting up the 443 virtual host for it?

**Comment by cycomarcooo** [comment]
It works well 
<img width="276" alt="screen shot 2016-04-05 at 20 55 00" src="https://cloud.githubusercontent.com/assets/1563647/14294331/bb95973c-fb70-11e5-8644-28923ab30943.png">

did you reload apache?

**Comment by ezekg** [comment]
Yes, that's how it looks for me as well. I can access it and accept it, but it's still not configured properly. I thought you configured yours in a way that wouldn't show up red within the browser.

I think using Let's Encrypt might be a better option, because we'll get a real certificate that won't show up red in the browser. I think this is better from a user's perspective, because right now, even if you can access it and the traffic is encrypted, it looks broken.

This might have additional side effects during development as well, so I think issuing a real cert on site creation is the best option. It shouldn't be too hard to set up via the CLI, since I already have the infrastructure to run commands on the virtual machine during the creation process.

**Comment by cycomarcooo** [comment]
Just saw that [roots.io/trellis](https://roots.io/trellis/docs/ssl/) (which is in my opinion the ultimate multi-env dev system), opted for let's encrypt and they wrote a very interesting doc for that. It's not straightforward and it will also raise an error by using their "fake" certificate intended for staging env.
Note that they also use snake-oil cert for dev purpose.

**Comment by cycomarcooo** [comment]
I'm using self-signed cert for while in my dev env and so far no side effect. By Googling a bit on that topic, it seems to be a good practice.

**Comment by ezekg** [comment]
Yeah, you're right. Let's Encrypt has to verify a domain before issuing a cert, so local development sites can't get a cert. I figured they had a way to generate a development cert you could install like the snake oil one, but I guess not. I'll look into getting your changes updated soon. Thanks for the links.

**Comment by ezekg** [comment]
Update `tj` and then run `cd ~/tj-vagrant && git pull origin master` to update the VM. [I added support for automatically generated SSL certs](https://github.com/ezekg/theme-juice-vvv#automatically-generated-self-signed-ssl-certs) for project's that support SSL (have a `*:443` virtual host). You'll need to accept the cert for each project, but it gives a valid lock in the browser:

![image](https://cloud.githubusercontent.com/assets/6979737/14320685/a3036148-fbdb-11e5-845a-ec5f67285bbb.png)

Let me know how it works!

**Comment by cycomarcooo** [comment]
Well done! I'll test it soon. Thanks

**Comment by cycomarcooo** [comment]
To try this new feature, I decided to get rid of all my previous tests then I removed all theme-juice related install on my machine started from zero.

I created a brand new project with `tj create`. Once the VM has been installed and provisioned, I went to the URL of project and faced a php error. I pretty sure it's not related to SSL feature because I faced it also with the previous VM version. Here is what I get: 
![screen shot 2016-04-07 at 11 39 32](https://cloud.githubusercontent.com/assets/1563647/14347315/c3febbb4-fcb6-11e5-859b-415e42446781.png)

It seems to be related to the network config, landrush?

**Comment by cycomarcooo** [comment]
I try to find the php error log file but can't find it. Of course, WP_DEBUG is set to true, but there is no php_errors.log in VM /srv/log/ . There is no debug.log in wp-content/ neither. Where is the php log file?

**Comment by ezekg** [comment]
It should be under `/var/log/`. You can try running `vagrant landrush ls` to see if there's any hanging records that didn't get removed properly, and if so you can remove them with `vagrant landrush rm {domain}`. When I get to the office, I'll see what I have in my notes, because that's happened to me before. It means that the VM can't connect to the Internet, so you probably can't `ping google.com` from inside the VM either. Might want to check out https://github.com/Varying-Vagrant-Vagrants/VVV/issues/211 and https://github.com/mitchellh/vagrant/issues/391.

> I sometimes get a timeout on cold starts (VM not even responding on pings), for some reason pinging from the VM to the host system fixes it:
> `vagrant ssh`
> `ping 192.168.50.1`

**Comment by ezekg** [comment]
If you continue to have problems, feel free to open up a new issue and we'll troubleshoot it.
