### ISSUE TITLE
Wordpress core file load-scripts.php causes an Internal server error (error 500)

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-vm#4]
Hi, while trying to access the upload.php page from Wordpress dashboard (Media > Library menu), images are not displayed because load-scripts.php causes an internal server error (500).

The wordpress site has been created with tj starter theme. This error does not occur with native vvv VM + tj-starter-theme WP site. This error does not occur on a deployed staging or prod server.

@ezekg  are you facing this issue? I reinstall the complete tool chain from scratch (tj-vvv, brand new site) but the error is still present.

<img width="1545" alt="screen shot 2016-04-10 at 17 20 23" src="https://cloud.githubusercontent.com/assets/1563647/14411173/b2ca8ba2-ff40-11e5-9c78-ecaa4c546e8a.png">
<img width="1012" alt="screen shot 2016-04-10 at 17 13 32" src="https://cloud.githubusercontent.com/assets/1563647/14411174/b5f57d3c-ff40-11e5-8ab7-00c156fc2d6a.png">

Here is the same page generated with native vvv VM. There is no error 500 and we can see the table header: 
<img width="1337" alt="screen shot 2016-04-10 at 16 49 29" src="https://cloud.githubusercontent.com/assets/1563647/14411245/b6b4749c-ff42-11e5-9d61-b47bf9b19b38.png">

**Comment by cycomarcooo** [comment]
The URL that causes the issue is super long: 
http://test-tj.dev/wp/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,admin-bar,underscore,shortcode,backbone,wp-util,wp-backbone,media-models,wp-plupload,jquery-ui-core,jquery-ui&load%5B%5D=-widget,jquery-ui-mouse,jquery-ui-sortable,mediaelement,wp-mediaelement,media-views,media-editor,media-audiovideo,mce-view,imgar&load%5B%5D=easelect,image-edit,media-grid,media,svg-painter,heartbeat,wp-auth-check&ver=4.3.1

Is it possible that either apache or php version embedded in the VM is unable to parse/handle it?

**Comment by cycomarcooo** [comment]
What a strange error... it does not happen with Safari and Firefox, only with Chrome...

**Comment by ezekg** [comment]
When you go to that link, what is the error? Have you checked the error logs? Have you modified `max_input_vars` in your `custom-php.ini` file or anything similar? I've never seen this error before.

**Comment by cycomarcooo** [comment]
I've done this test strainght out of the box with a brand new VM and a wp site created with tj-starter template. Nothing modified in custom-php.ini.
Same site with vvv box -> no problem

apache error log shows:
[core:alert] [pid 29859] [client 192.168.50.1:54587] /srv/www/tj-test-safari/.htaccess: Invalid command 'text/css', perhaps misspelled or defined by a module not included in the server configuration, referer: http://test-safari.dev/wp/wp-admin/upload.php

... but modules are loaded properly.

**Comment by cycomarcooo** [comment]
The issue comes from .htaccess. Cant see why yet but by removing all but the very first part needed by WP, it works.

**Comment by ezekg** [comment]
Ah, _that_ pesky error. I've never had this issue before with the VM, but have hit the issue on previous projects when deploying to production. It's something to do with Apache that I can't figure out. I know it seems weird, but try moving [this line](https://github.com/ezekg/theme-juice-starter/blob/master/.htaccess?ts=2#L385) up 1 line, and then saving the `.htaccess` file. Don't ask me how I figured that out. Let me know if that fixes your issue, and if you know what is happening there.

**Comment by cycomarcooo** [comment]
Removing this block solves the problem: 

```
<IfModule mod_filter.c>
    AddOutputFilterByType DEFLATE "application/atom+xml" \
                                  "application/javascript" \
                                  "application/json" \
                                  "application/ld+json" \
                                  "application/manifest+json" \
                                  "application/rdf+xml" \
                                  "application/rss+xml" \
                                  "application/schema+json" \
                                  "application/vnd.geo+json" \
                                  "application/vnd.ms-fontobject" \
                                  "application/x-font-ttf" \
                                  "application/x-javascript" \
                                  "application/x-web-app-manifest+json" \
                                  "application/xhtml+xml" \
                                  "application/xml" \
                                  "font/eot" \
                                  "font/opentype" \
                                  "image/bmp" \
                                  "image/svg+xml" \
                                  "image/vnd.microsoft.icon" \
                                  "image/x-icon" \
                                  "text/cache-manifest" \
                                  "text/css" \
                                  "text/html" \
                                  "text/javascript" \
                                  "text/plain" \
                                  "text/vcard" \
                                  "text/vnd.rim.location.xloc" \
                                  "text/vtt" \
                                  "text/x-component" \
                                  "text/x-cross-domain-policy" \
                                  "text/xml"

  </IfModule>
```

**Comment by cycomarcooo** [comment]
Ok, it seems there is a problem with too long declaration of this type. By replacing the mentioned block by the following one solves the problem:

```
  <IfModule mod_filter.c>
    AddOutputFilterByType DEFLATE "application/atom+xml"
    AddOutputFilterByType DEFLATE "application/javascript"
    AddOutputFilterByType DEFLATE "application/json"
    AddOutputFilterByType DEFLATE "application/ld+json"
    AddOutputFilterByType DEFLATE "application/manifest+json"
    AddOutputFilterByType DEFLATE "application/rdf+xml"
    AddOutputFilterByType DEFLATE "application/rss+xml"
    AddOutputFilterByType DEFLATE "application/schema+json"
    AddOutputFilterByType DEFLATE "application/vnd.geo+json"
    AddOutputFilterByType DEFLATE "application/vnd.ms-fontobject"
    AddOutputFilterByType DEFLATE "application/x-font-ttf"
    AddOutputFilterByType DEFLATE "application/x-javascript"
    AddOutputFilterByType DEFLATE "application/x-web-app-manifest+json"
    AddOutputFilterByType DEFLATE "application/xhtml+xml"
    AddOutputFilterByType DEFLATE "application/xml"
    AddOutputFilterByType DEFLATE "font/eot"
    AddOutputFilterByType DEFLATE "font/opentype"
    AddOutputFilterByType DEFLATE "image/bmp"
    AddOutputFilterByType DEFLATE "image/svg+xml"
    AddOutputFilterByType DEFLATE "image/vnd.microsoft.icon"
    AddOutputFilterByType DEFLATE "image/x-icon"
    AddOutputFilterByType DEFLATE "text/cache-manifest"
    AddOutputFilterByType DEFLATE "text/css"
    AddOutputFilterByType DEFLATE "text/html"
    AddOutputFilterByType DEFLATE "text/javascript"
    AddOutputFilterByType DEFLATE "text/plain"
    AddOutputFilterByType DEFLATE "text/vcard"
    AddOutputFilterByType DEFLATE "text/vnd.rim.location.xloc"
    AddOutputFilterByType DEFLATE "text/vtt"
    AddOutputFilterByType DEFLATE "text/x-component"
    AddOutputFilterByType DEFLATE "text/x-cross-domain-policy"
    AddOutputFilterByType DEFLATE "text/xml"

  </IfModule>
```

**Comment by ezekg** [comment]
Awesome. Most of that file is taken directly from [here](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess?ts=2#L740-L772). Could you make a pull request with that change?
