### ISSUE TITLE
Vagrantfile do not call tools.sh

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-vm#6]
Hi @ezekg, I'm just trying the latest version of tj and tj-vm and I found that tools.sh is not called from the Vagrantfile [(see here](https://github.com/ezekg/theme-juice-vm/blob/master/Vagrantfile#L101)). 
Then, tj backup and other command will not work.

Brs

**Comment by ezekg** [comment]
Sorry about that, I had a duplicate of one of the other provisioners. Do a `git pull` and then run `vagrant provision`. I'll update the Atlas box later on today so the box will come pre-provisioned with the fix.
