### ISSUE TITLE
hostname should be graft.dev instead of graft

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-vm#7]
I noticed that when I try to access graft.dev I get an error from my browser (collision error). Looking at my /etc/hosts file, I got:

```
192.168.50.4  graft # VAGRANT: xxx (default) / xxx
```

I guess it should be replaced by: 

```
192.168.50.4  graft.dev # VAGRANT: xxx (default) / xxx
```

by changing this [line](https://github.com/ezekg/theme-juice-vm/blob/master/Vagrantfile#L21)?

**Comment by ezekg** [comment]
Yeah, you're probably right. Not sure why I left off the `.dev`. I'll have it fixed in the next update.

**Comment by ezekg** [comment]
Fixed in latest version!
