### ISSUE TITLE
default/index.php is still looking for vvv.dev

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-vm#8]
Hi, [here is a remaining call to vvv.dev](https://github.com/ezekg/theme-juice-vm/blob/master/Vagrantfile#L21) which cause an error.

**Comment by ezekg** [comment]
You're right, I completely forgot about that file. I'll have it fixed in the next round of updates.

**Comment by ezekg** [comment]
Fixed in latest.
